version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: discord.js
    versions:
    - 12.5.1
    - 12.5.2
  - dependency-name: "@discordjs/opus"
    versions:
    - 0.4.0
  - dependency-name: ytdl-core
    versions:
    - 4.4.5
